### PR TITLE
dgtal 1.1

### PR DESCRIPTION
**Pull request by Karganys**
Upgrade to `dgtal` 1.1 (https://github.com/DGtal-team/DGtal/releases/tag/1.1)

:octocat:

### CODE REVIEW

**Comment by Karganys** [comment]
Travis has failed, but seems not linked to my PR:
```
🍺  /usr/local/Cellar/autoconf/2.71: 75 files, 3.2MB, built in 8 seconds
==> Installing openjdk
==> ./configure --without-version-pre --without-version-opt --with-version-build==> make images
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Review by dcoeurjo — APPROVED** [review]
Mmmouais.. did you sign the contributor license agreement ?
🐇

**Comment by dcoeurjo** [comment]
Thx🍺

**Comment by dcoeurjo** [comment]
Let me check:/

**Pull request merged**
